### PR TITLE
sort encryption options

### PR DESCRIPTION
**Pull request by timogoebel**
... we should sort the hash keys so that the file does not change every single puppet run. :-)

### CODE REVIEW

**Comment by duritong** [comment]
Afair we need to sort on the keys, as sort on a hash on 1.8 doesb't do what you expect it to do.

**Comment by timogoebel** [comment]
@duritong : What would you prefer instead?

<% @adapter_options.sort_by {|key, value| key}.each do |key,value| -%>

**Comment by duritong** [comment]
Or just like `@adapter_options.keys.sort.each{|k| @adapter_options[k] }`

**Comment by timogoebel** [comment]
Thanks, @duritong ! I updated the code. What do you think?

**Comment by duritong** [comment]
Thanks! Lgtm

**Pull request merged**
